#! /bin/sh

if [ -n "$1" ]; then
    py_ver="$1"
else
    py_ver=2
fi

echo AOEU $py_ver

p=`command -v python$py_ver`
if [ $? -ne 0 ]; then
    p=`command -v python`
    if [ $? -ne 0 ]; then
        echo "error: cannot find Python $py_ver binary" 1>&2
        exit 1
    fi
fi

echo AOEU $p

"$p" setup.py build
